version: 2.1
commands: # List of commands
  install_deps: # Installing dependencies
    steps: # List of steps
      - run: # Run the commands on line 7 called 'Install Dependencies'
          name: Install Dependencies
          command: |
            cd src
            npm install


jobs: # List of jobs
  build: # List of builds
    docker: # Creating a Docker container
      - image: circleci/node:lts # Installing Circleci image on Docker container
    steps: # Listing steps
      - checkout
      - install_deps # Calling upon command called 'install_deps'
      - run:
          name: Test Unit
          command: |
            cd src
            npm run test-unit


workflows:
  version: 2
  build-test-package:
    jobs:
      - build