version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run: run tests
      command: |
        npm run unit-tests
         
workflows:
  version: 2
  build-test-package:
    jobs:
      - build