version: 2.1
commands: # List of commands
  install_deps: # Installing dependencies
    steps: # List of steps
      - run: # Run the commands on line 7 called 'Install Dependencies'
          name: Install Dependencies
          command: |
            cd src
            npm install


jobs: # List of jobs
  build: # List of builds
    docker: # Creating a Docker container
      - image: circleci/node:lts # Installing Circleci image on Docker container
    steps: # Listing steps
      - checkout
      - install_deps # Calling upon command called 'install_deps'
      - run: # Running(19) commands(21), named 'Test Unit'(20)
          name: Test Unit
          command: | # Change directory to 'src', npm will run script 'test-unit' from 'package.json'
            cd src
            npm run test-unit
      - run: # Running(24) commands(26), named 'Lint'(25)
          name: Test Lint
          command: | # Change directory to 'src', npm will run script 'test-lint' from 'package.json'
            cd src
            npm run test-lint


workflows:
  version: 2
  build-test-package:
    jobs:
      - build