version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout
      - install_deps
      - run: 
          name: run tests
          command: |
            mkdir -p test-output
            npm run unit-tests
      - store_test_results:
          path: test-output
    
          
workflows:
  version: 2
  build-test-package:
    jobs:
      - build